"""Part 2 — object detection: COCO handling, YOLO/D-FINE training and comparison."""

from .coco import (
    CocoAudit,
    annotations_by_image,
    audit_coco,
    build_image_index,
    dominant_class_per_image,
    export_split_to_coco,
    find_coco_json,
    sanitize_bbox,
    validate_exported_coco,
)
from .compare import (
    DetectorResult,
    classify_errors,
    comparison_table,
    error_summary,
    iou,
    plot_metric_comparison,
    plot_predictions,
)
from .convert import (
    DetectionSplits,
    audit_yolo_dataset,
    build_yolo_dataset,
    coco_bbox_to_yolo,
    read_yolo_labels,
    split_detection_dataset,
    summarize_splits,
)
from .dfine import (
    DFineConfigPaths,
    find_best_checkpoint,
    parse_coco_metrics,
    parse_training_history,
    run_dfine,
    write_dfine_configs,
)
from .yolo import (
    evaluate_yolo,
    extract_yolo_metrics,
    plot_training_curves,
    predict_yolo,
    read_training_curves,
    train_yolo,
)

__all__ = [
    "CocoAudit",
    "DFineConfigPaths",
    "DetectionSplits",
    "DetectorResult",
    "annotations_by_image",
    "audit_coco",
    "audit_yolo_dataset",
    "build_image_index",
    "build_yolo_dataset",
    "classify_errors",
    "coco_bbox_to_yolo",
    "comparison_table",
    "dominant_class_per_image",
    "error_summary",
    "evaluate_yolo",
    "export_split_to_coco",
    "extract_yolo_metrics",
    "find_best_checkpoint",
    "find_coco_json",
    "iou",
    "parse_coco_metrics",
    "parse_training_history",
    "plot_metric_comparison",
    "plot_predictions",
    "plot_training_curves",
    "predict_yolo",
    "read_training_curves",
    "read_yolo_labels",
    "run_dfine",
    "sanitize_bbox",
    "split_detection_dataset",
    "summarize_splits",
    "train_yolo",
    "validate_exported_coco",
    "write_dfine_configs",
]
